Abertos = COALESCE(
	     CALCULATE(
                COUNT('GLPI'[id]),
                   USERELATIONSHIP('GLPI'[DtAbertura],
                                   'Calendário'[Data]) 
                       )
		,0)